### ISSUE TITLE
视频372M 时长三分半 加载的时候就ANR了 ，请问这个怎么解决

### ISSUE THREAD

**Issue by wuxinggege008** [iknow4/Android-Video-Trimmer#10]
05-28 12:02:20.548 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: cn.carya, PID: 17304
                                     java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 882064 bytes
                                         at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4022)
                                         at android.os.Handler.handleCallback(Handler.java:789)
                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                         at android.os.Looper.loop(Looper.java:164)
                                         at android.app.ActivityThread.main(ActivityThread.java:6642)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                      Caused by: android.os.TransactionTooLargeException: data parcel size 882064 bytes
                                         at android.os.BinderProxy.transactNative(Native Method)
                                         at android.os.BinderProxy.transact(Binder.java:751)
                                         at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4670)
                                         at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4014)
                                         at android.os.Handler.handleCallback(Handler.java:789) 
                                         at android.os.Handler.dispatchMessage(Handler.java:98) 
                                         at android.os.Looper.loop(Looper.java:164) 
                                         at android.app.ActivityThread.main(ActivityThread.java:6642) 
                                         at java.lang.reflect.Method.invoke(Native Method) 
                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by iknow4** [comment]
@wuxinggege008 我可以拥有你的视频用于测试么？

**Comment by wuxinggege008** [comment]
@iknow4 
你好 视频已经上传到百度云  
链接: https://pan.baidu.com/s/1-oBceNJpgO67u9feD4c3VA  密码: tmpk

**Comment by iknow4** [comment]
好的，谢谢！

**Comment by iknow4** [comment]
@wuxinggege008  我下载了你的视频是可以正确加载的。

**Comment by iknow4** [comment]
@wuxinggege008 使用你提供的视频进行测试，在视频播放的时候是有点问题。

**Comment by iknow4** [comment]
问题关闭，如果需要，可以重新打开。
