### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by LCJustin** [iknow4/Android-Video-Trimmer#13]
点击一个视频进入出现OOM：
AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.iknow.android, PID: 2743
                                                                 java.lang.OutOfMemoryError: Failed to allocate a 1054452 byte allocation with 393640 free bytes and 384KB until OOM
                                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                     at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:1070)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:1040)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:944)
                                                                     at com.iknow.android.widget.RangeSeekBarView.onDraw(RangeSeekBarView.java:156)
                                                                     at android.view.View.draw(View.java:17250)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16215)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16210)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16210)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16210)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.draw(View.java:17253)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16215)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16210)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16210)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16210)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16210)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16210)
                                                                     at android.view.View.draw(View.java:17016)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16210)

**Comment by iknow4** [comment]
@LCJustin  好，谢谢反馈，我查下。
