### ISSUE TITLE
我这面执行为什么走 失败方法 并且告诉我 FFmpeg: Exception while trying to run: [/data/user/0/cn.wdcloud.luke/files/ffmpeg, -ss, 00:00, -t, 00:00:05, -accurate_seek, -i, /storage/emulated/0/Android/data/cn.wdcloud.luke/files/Video/2019-05-16-15-12-54.mp4, -codec, copy, -avoid_negative_ts, 1, /storage/emulated/0/Android/data/cn.wdcloud.luke/files/Video/trim_2019-05-16-15-13-13.mp4]     java.io.IOException: Cannot run program "/data/user/0/项目名称/files/ffmpeg": error=2, No such file or directory

### ISSUE THREAD

**Issue by wangyikai1234567** [iknow4/Android-Video-Trimmer#41]
FFmpeg: Exception while trying to run: [/data/user/0/项目名称//files/ffmpeg, -ss, 00:00, -t, 00:00:05, -accurate_seek, -i, /storage/emulated/0/Android/data/项目名称/files/Video/2019-05-16-15-12-54.mp4, -codec, copy, -avoid_negative_ts, 1, /storage/emulated/0/Android/data/项目名称//files/Video/trim_2019-05-16-15-13-13.mp4]
    java.io.IOException: Cannot run program "/data/user/0项目名称//files/ffmpeg": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
        at nl.bravobit.ffmpeg.ShellCommand.run(ShellCommand.java:15)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:43)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:12)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:128)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
        at nl.bravobit.ffmpeg.ShellCommand.run(ShellCommand.java:15) 
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:43) 
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:12) 
        at android.os.AsyncTask$2.call(AsyncTask.java:304) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762)

**Comment by iknow4** [comment]
@wangyikai1234567 
ava.io.IOException: Cannot run program "/data/user/0项目名称//files/ffmpeg": error=2, No such file or directory
请检查一下目录或者文件夹是否有创建。

**Comment by wangyikai1234567** [comment]
确定已经创建 ------------------ 原始邮件 ------------------
发件人: "WHOKNOWME"<notifications@github.com>
发送时间: 2019年5月16日(星期四) 下午5:27
收件人: "iknow4/Android-Video-Trimmer"<Android-Video-Trimmer@noreply.github.com>;
抄送: "wangyikai1234567"<2285281993@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [iknow4/Android-Video-Trimmer] 我这面执行为什么走 失败方法 并且告诉我 FFmpeg: Exception while trying to run: [/data/user/0/cn.wdcloud.luke/files/ffmpeg, -ss, 00:00, -t, 00:00:05, -accurate_seek, -i, /storage/emulated/0/Android/data/cn.wdcloud.luke/files/Video/2019-05-16-15-12-54.mp4, -codec, copy, -avoid_negative_ts, 1, /storage/emulated/0/Android/data/cn.wdcloud.luke/files/Video/trim_2019-05-16-15-13-13.mp4]     java.io.IOException: Cannot run program "/data/user/0/项目名称/files/ffmpeg": error=2, No such file or directory (#41)



@wangyikai1234567
 ava.io.IOException: Cannot run program "/data/user/0项目名称//files/ffmpeg": error=2, No such file or directory
 请检查一下目录或者文&#x4EF6;夹是否有创建。
 
&mdash;

**Comment by iknow4** [comment]
@wangyikai1234567 
 "/data/user/0项目名称//files/ffmpeg" 
认真看下，这个文件路径的格式似乎不太对吧。

**Comment by wangyikai1234567** [comment]
对，我其实就是迷茫这个路径。ffmpeg应该不会创建但我本地啊，然后我之前用其他的，他们的命令前都要加上“ffmpeg”,但是咱们项目中好像不需要------------------ 原始邮件 ------------------
发件人: "WHOKNOWME"<notifications@github.com>
发送时间: 2019年5月16日(星期四) 晚上6:04
收件人: "iknow4/Android-Video-Trimmer"<Android-Video-Trimmer@noreply.github.com>;
抄送: "wangyikai1234567"<2285281993@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [iknow4/Android-Video-Trimmer] 我这面执行为什么走 失败方法 并且告诉我 FFmpeg: Exception while trying to run: [/data/user/0/cn.wdcloud.luke/files/ffmpeg, -ss, 00:00, -t, 00:00:05, -accurate_seek, -i, /storage/emulated/0/Android/data/cn.wdcloud.luke/files/Video/2019-05-16-15-12-54.mp4, -codec, copy, -avoid_negative_ts, 1, /storage/emulated/0/Android/data/cn.wdcloud.luke/files/Video/trim_2019-05-16-15-13-13.mp4]     java.io.IOException: Cannot run program "/data/user/0/项目名称/files/ffmpeg": error=2, No such file or directory (#41)



@wangyikai1234567
 "/data/user/0项目名称//files/ffmpeg"
 认真看下，这个文&#x4EF6;路径的格式似乎不太对吧。
 
&mdash;
