### ISSUE TITLE
点击截取完成后直接崩溃

### ISSUE THREAD

**Issue by vincecarterhu** [iknow4/Android-Video-Trimmer#5]
oppo  A59m

**Comment by iknow4** [comment]
请提供一下你完整的崩溃日志，谢谢！

发自我的 iPhone

**Comment by vincecarterhu** [comment]
com.iknow.android E/ActivityThread: Performing stop of activity that is not resumed: {com.iknow.android/com.iknow.android.VideoSelectActivity}
                                                                   java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.iknow.android/com.iknow.android.VideoSelectActivity}
                                                                       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3693)
                                                                       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3789)
                                                                       at android.app.ActivityThread.access$1200(ActivityThread.java:187)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                       at android.os.Looper.loop(Looper.java:210)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5809)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by iknow4** [comment]
@vincecarterhu  你的问题还存在吗？
