### ISSUE TITLE
Stuck on the trimming video dialog in Samsung phone.

### ISSUE THREAD

**Issue by passenger-earth** [iknow4/Android-Video-Trimmer#56]
Thank you for the great project . I am facing a issue. The app remains stuck in the trimming video dialog after i click finish , i am testing it on a samsung galaxy s7 phone. Any suggestions on how to solve the problem?

**Comment by iamkdblue** [comment]
Thank for this great project.

I am running this example app in my Android 10 (k20 pro)
video stuck at dialog, and i got this error


```
2020-07-22 12:24:48.163 28283-29116/com.iknow.android E/FFmpeg: Exception while trying to run: [/data/user/0/com.iknow.android/files/ffmpeg, -ss, 00:00, -t, 00:00:10, -accurate_seek, -i, /storage/emulated/0/DCIM/Horizon/MOV_2020-07-20_at_15-42-27.mp4, -codec, copy, -avoid_negative_ts, 1, /storage/emulated/0/Android/data/com.iknow.android/cache/trimmedVideo_20200722_122448.mp4]
    java.io.IOException: Cannot run program "/data/user/0/com.iknow.android/files/ffmpeg": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at nl.bravobit.ffmpeg.ShellCommand.run(ShellCommand.java:15)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:43)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:12)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at nl.bravobit.ffmpeg.ShellCommand.run(ShellCommand.java:15) 
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:43) 
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:12) 
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by zxb123456** [comment]
您好,这个权限问题，解决了吗？有什么好方法吗？

**Comment by iamkdblue** [comment]
@zxb123456 i solved this issue by use SDK 28, this error comes in SDK 29, so its temporary solution.
Just change `compileSdkVersion 29` to `compileSdkVersion 28`

**Comment by zxb123456** [comment]
您好，方便留个微信或者qq吗？这个降低到28编译总是报android:requestLegacyExternalStorage 这个找不到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iknow4/Android-Video-Trimmer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 晚上8:13
收件人:&nbsp;"iknow4/Android-Video-Trimmer"<Android-Video-Trimmer@noreply.github.com&gt;;
抄送:&nbsp;"摩天轮￡爱"<357687868@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [iknow4/Android-Video-Trimmer] Stuck on the trimming video dialog in Samsung phone. (#56)





 
@zxb123456 i solved this issue by use SDK 28, this error comes in SDK 29, so its temporary solution.
 Just change compileSdkVersion 29 to compileSdkVersion 28

**Comment by iamkdblue** [comment]
Yes just remove `android:requestLegacyExternalStorage ` and run.

**Comment by zxb123456** [comment]
我这边已经将targetSdkVersion 28 and  compileSdkVersion =28 进行设置了。但是还是报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iknow4/Android-Video-Trimmer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 晚上8:21
收件人:&nbsp;"iknow4/Android-Video-Trimmer"<Android-Video-Trimmer@noreply.github.com&gt;;
抄送:&nbsp;"摩天轮￡爱"<357687868@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [iknow4/Android-Video-Trimmer] Stuck on the trimming video dialog in Samsung phone. (#56)





 
Yes just remove android:requestLegacyExternalStorage  and run.

**Comment by iamkdblue** [comment]
WeChat or QQ ban in india😜  and remove this android:requestLegacyExternalStorage

**Comment by Mr-Ramzan** [comment]
![image](https://user-images.githubusercontent.com/36961360/91013550-467a5700-e601-11ea-84e3-a48bce9d5315.png)

** I am also facing similar Issue**

below log with no err 
`D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728
D/VideoTrimmerView: updateVideoProgress currentPosition = 9728`


**This just happen Infinitely** 

some time it gives 0 as the current position

**Comment by hamaianh** [comment]
me too, I also have the same situation on some devices. Plz help me fix it if we use compileSdkVersion > 28!
java.io.IOException: Cannot run program "/data/user/0/com.iknow.android/files/ffmpeg": error=13, Permission denied
Thanks so much!

**Comment by lkhore** [comment]
any update on this
