### ISSUE TITLE
点击完成闪退

### ISSUE THREAD

**Issue by JsonWong87** [iknow4/Android-Video-Trimmer#6]
FATAL EXCEPTION: main
                                                                 Process: com.iknow.android, PID: 6953
                                                                 java.lang.RuntimeException: Only one Looper may be created per thread
                                                                     at android.os.Looper.prepare(Looper.java:88)
                                                                     at android.os.Looper.prepare(Looper.java:83)
                                                                     at com.iknow.android.TrimmerActivity.onFinishTrim(TrimmerActivity.java:79)
                                                                     at com.iknow.android.utils.TrimVideoUtil$1.onSuccess(TrimVideoUtil.java:61)
                                                                     at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.onPostExecute(FFmpegExecuteAsyncTask.java:68)
                                                                     at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.onPostExecute(FFmpegExecuteAsyncTask.java:10)
                                                                     at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                     at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JsonWong87** [comment]
if (Looper.myLooper()==null)
    Looper.prepare();

这样就行了
